# Generated by Django 4.2.5 on 2023-10-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_assignment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='assignment_file',
        ),
    ]
