# Generated by Django 4.2.5 on 2023-10-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_student_delete_assignment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='diploma',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='assign'),
        ),
    ]
