# Generated by Django 4.2.5 on 2023-10-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_myuploadfile_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadfile',
            name='desc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
