# Generated by Django 4.2.5 on 2023-10-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_myuploadfile_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfile',
            name='desc',
        ),
    ]
