# Generated by Django 4.2.5 on 2023-10-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_myuploadfile_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadfile',
            name='f_desc',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
