# Generated by Django 4.2.5 on 2023-10-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_myuploadfile_f_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadfile',
            name='first_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
