# Generated by Django 4.2.5 on 2023-10-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_myuploadfile_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='myuploadfees',
            fields=[
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default=None, max_length=20, null=True)),
                ('f_desc', models.CharField(default=None, max_length=255, null=True)),
                ('f_name', models.CharField(max_length=255)),
                ('myfiles', models.FileField(upload_to='')),
            ],
        ),
    ]
