# Generated by Django 4.2.5 on 2023-10-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_myuploadfees_totalfees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfees',
            name='totalfees',
        ),
    ]
