# Generated by Django 4.2.5 on 2023-10-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_myuploadfees_totalfees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuploadfees',
            name='f_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
