# Generated by Django 4.2.5 on 2023-10-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_myuploadfile_f_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadfile',
            name='date_field',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
