# Generated by Django 4.2.5 on 2023-10-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_myuploadfile_date_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuploadfile',
            name='date_field',
        ),
    ]
