# Generated by Django 4.2.5 on 2023-10-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_remove_myuploadfile_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuploadfile',
            name='date_field',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
