# Generated by Django 4.2.5 on 2023-10-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_file_upload_file_name2_file_upload_my_file2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_upload',
            name='file_name2',
        ),
        migrations.RemoveField(
            model_name='file_upload',
            name='my_file2',
        ),
    ]
