# Generated by Django 4.2.5 on 2023-10-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_remove_file_upload_file_name2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='myclassnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=30, null=True)),
                ('date_field', models.DateField(auto_now=True)),
                ('file_desc', models.CharField(default=None, max_length=255, null=True)),
                ('file_name', models.CharField(max_length=55, null=True)),
                ('status', models.CharField(max_length=12, null=True)),
                ('myfiles', models.FileField(upload_to='')),
            ],
        ),
    ]
