# Generated by Django 4.2.5 on 2023-10-31 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_assignment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myuploadfile',
            new_name='myuploadjournels',
        ),
    ]
